<a href="https://colab.research.google.com/github/fatidevt/data-skills-journey/blob/main/numpy/exrcices/numpy_exercices.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Beginner Exercises

Create a 1D array [10, 20, 30, 40, 50] with dtype int16. Print its shape, dtype, itemsize, and nbytes.


In [ ]:
import numpy as np
a = np.array([10, 20, 30, 40, 50], dtype='int16')
print("shape (row, col) : ", a.shape)
print("data type : ", a.dtype)
print("nb of bytes for an element : " , a.itemsize)
print("nb of elements : ", a.size)
print("nb of bytes of the array : ", a.nbytes)

Create a 3×4 matrix filled entirely with the number 7, using np.full.


In [ ]:
b = np.full((3,4) , 7)
print(b)

Given arr = np.array([[1,2,3],[4,5,6],[7,8,9]]), extract the middle row and the last column separately.


In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
mid = arr[1, :]
print(mid)
last_col = arr[ : , 2]
print(last_col)

Create a 5×5 identity matrix, then multiply every element by 3.


In [ ]:
c = np.identity(5)
new = c * 3
print(new)

Given temps = np.array([70,75,68,90,85,60,95]), use boolean masking to

(a) get only the temps above 80, and

(b) count how many days that was.



In [ ]:
temps = np.array([70,75,68,90,85,60,95])
print(temps > 80)
count = np.sum(temps > 80)
print(count)

# Intermediate Exercises

Grades: You have a 5 students × 3 tests array of scores. Compute each student's average (row-wise) and each test's average (column-wise), then find which student has the highest overall average.


In [ ]:
# row : axis = 1
# column : axis = 0
grades = np.array((
    [15,16,10],
    [10,15,11],
    [15,18,19],
    [12,16,17],
    [11,12,18]
    ))
print(grades)
student_avg = np.average(grades, axis = 1)
print("student average" ,student_avg)
test_av = np.average(grades, axis = 0)
print("test average" ,test_av)

best_student = np.argmax(student_avg)
print("\nBest student index:", best_student)
print("Highest average:", student_avg[best_student])

Image brightness: Given a small 2D array representing a grayscale image (values 0–255), write code that increases brightness by adding 40 to every pixel without exceeding 255 (hint: np.clip), then creates a binary mask of which pixels are "bright" (>200).


In [ ]:
grayscale = np.array([
    [155,120,188,192,205,237],
    [19,240,198,129,220,158],
    [129,125,212,85,75,89]
])

brightened = np.clip(grayscale + 40, 0, 255)

bright_mask = brightened > 200

print("\nOriginal image:")
print(grayscale)

print("\nBrightened image:")
print(brightened)

print("\nBright pixels (>200):")
print(bright_mask)

Sales report: You have a flat 1D array of 36 numbers = 3 products × 12 months of sales.

Reshape it into a (3, 12) matrix.

Compute total sales per product and per month.

Then, given a weight vector for the 3 products (e.g. [0.5, 0.3, 0.2] representing profit margins), use np.matmul to get a weighted profit total per month.



In [ ]:

sales = np.array([
    12,85,3,67,45,91,
    28,74,50,11,96,32,
    7,88,60,23,41,19,
    95,14,37,82,5,56,
    71,49,27,63,90,10,
    39,58,1,77,22,84
])

sales = sales.reshape(3,12)

print("\nSales matrix:")
print(sales)

# Total sales per product
product_total = np.sum(sales, axis=1)

# Total sales per month
month_total = np.sum(sales, axis=0)

print("\nTotal sales per product:")
print(product_total)

print("\nTotal sales per month:")
print(month_total)

# Profit margins
weights = np.array([0.5, 0.3, 0.2])

weighted_profit = np.matmul(weights, sales)

print("\nWeighted monthly profit:")
print(weighted_profit)

#  Challenge Problem

You have a 2D array of exam scores, shape (students, subjects) — e.g. 4 students × 5 subjects.

Without using any Python loops, drop the lowest score in each student's row (set it to 0) and then recompute each student's row sum with the dropped score excluded.


Hint: np.argmin(arr, axis=1) gives you the column index of the lowest score per row — you'll need to pair that with np.arange(arr.shape[0]) to do fancy indexing like arr[[0,1,2,3], [col0,col1,col2,col3]].

In [73]:
scores = np.array([
    [15,9,18,19,20],
    [19,20,19,10,15],
    [11,13,12,15,17],
    [15,12,18,19,10]
])

# column index of the lowest score in each row
min_indices = np.argmin(scores, axis=1)
print("Min indices", min_indices)
# create row indices for advanced indexing
row_indices = np.arange(scores.shape[0])
print("Row indices", row_indices)

# set the lowest score in each row to 0
scores[row_indices, min_indices] = 0

print("New Scores",scores)

sum = np.sum(scores, axis=1)
print("sum res for each student",sum)


Min indices [1 3 0 4]
Row indices [0 1 2 3]
New Scores [[15  0 18 19 20]
 [19 20 19  0 15]
 [ 0 13 12 15 17]
 [15 12 18 19  0]]
sum res for each student [72 73 57 64]


`np.argmin(arr, axis=1)`

Returns the COLUMN INDEX of the smallest value in each row.

It does NOT return the smallest values themselves.


`np.arange(scores.shape[0])`

Creates an array of row indices from 0 to the number of rows - 1.

Used with fancy indexing to access one element from each row.